# Generated by Django 3.0.8 on 2020-08-15 06:35

import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('feed', '0006_auto_20200815_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=stdimage.models.JPEGField(upload_to='path/to/img'),
        ),
    ]
